### ISSUE TITLE
Panel files.

### ISSUE THREAD

**Issue by tomsteed** [Testbild-synth/HAGIWO-029-033-Eurorack-quantizer#2]
Hi,
Sorry i don't have your email to ask the occational question.
Anyway, have the panel files been removed from the repository.
Thanks.

**Comment by Testbild-synth** [comment]
They do not seem to be there for some reason, even though I think they
should be there and even though I'm pretty sure other people have built
this thing before. Give me a second I'll just add them.

tomsteed ***@***.***> schrieb am Fr., 10. März 2023, 05:10:

**Comment by Testbild-synth** [comment]
closed panel is there now

**Comment by dlakwi** [comment]
The panel svg and gerbers are there but could the KiCad design files also be uploaded?
